// The one-page portfolio (roteiro-secoes.md §01–08), written once and rendered per language.
// Section ids stay the same in every language: the scripts in src/js find them by id.
import { projects } from '../../src/data/projects.js';
import { esc, img, head, header, footer, studyUrl, LINKEDIN, LOCALES, GLOBE } from './shared.mjs';

const ARROW = (id) => `<svg class="icon" aria-hidden="true"><use href="#${id}" /></svg>`;
const by = Object.fromEntries(projects.map((p) => [p.slug, p]));

// the text block of a study inside the page (kicker, name, sector, line, role, two links)
function caseBlock({ p, s, t, loc, button }) {
  const proto = p.prototype
    ? `
                <a class="btn btn--quiet" href="${p.prototype}" target="_blank" rel="noopener">
                  <span>${esc(t.work.prototype)}</span>
                  ${ARROW('i-external')}
                  <span class="sr-only">${esc(t.newTab)}</span>
                </a>`
    : '';
  return `<div class="case" data-reveal>
              <p class="eyebrow case-kicker"><span>${p.number} / 0${projects.length}</span> ${esc(t.work.kicker)}</p>
              <h3 class="case-title" id="${p.slug}-title">${esc(p.name)}</h3>
              <p class="case-sector">${esc(s.sector)}</p>
              <p class="case-lead">${esc(s.proposal)}</p>
              <p class="case-role"><span>${esc(t.work.role)}</span> ${esc(s.role)}</p>
              <div class="actions">
                <a class="btn ${button}" href="${studyUrl(loc, p.slug)}">
                  <span>${esc(t.work.explore)}</span>
                  ${ARROW('i-arrow-right')}
                </a>${proto}
              </div>
            </div>`;
}

function card({ p, s, t, loc }) {
  return `            <li>
              <a class="study-card" href="${studyUrl(loc, p.slug)}" data-reveal>
                <figure>
                  <img src="${img(`window-${p.slug}-640`)}" srcset="${img(`window-${p.slug}-640`)} 640w, ${img(`window-${p.slug}-1024`)} 1024w" sizes="(min-width: 1024px) 30vw, (min-width: 768px) 46vw, 92vw" width="640" height="400" alt="" loading="lazy" decoding="async" />
                </figure>
                <span class="study-meta">
                  <span class="study-num">${p.number}</span>
                  <span class="study-name">${esc(p.name)}</span>
                  <span class="study-line">${esc(s.tagline)} · ${esc(s.sector.split(' · ')[0])}</span>
                  <span class="study-tag">${esc(t.list.tag)}</span>
                </span>
              </a>
            </li>`;
}

function role(r) {
  const partner = r.partner ? ` <span class="role-partner">/ ${esc(r.partner)}</span>` : '';
  return `<li class="role" data-reveal>
                  <p class="role-meta"><span>${esc(r.years)}</span> ${esc(r.place)}</p>
                  <h4 class="role-org">${esc(r.org)}${partner}</h4>
                  <p class="role-title">${esc(r.title)}</p>
                  <ul class="role-points">
                    ${r.points.map((x) => `<li>${esc(x)}</li>`).join('\n                    ')}
                  </ul>
                </li>`;
}

export function home(loc, t) {
  const S = t.studies;
  const c = (slug, button) => caseBlock({ p: by[slug], s: S[slug], t, loc, button });
  const alternates = Object.fromEntries(LOCALES.map((l) => [l.code, l.home]));
  const index = projects
    .map((p) => `<li><a href="#${p.slug}"><span>${p.number}</span> ${esc(p.name)}</a></li>`)
    .join('\n              ');
  const rail = projects
    .map((p) => `<li><a href="#${p.slug}" data-rail-link="${p.slug}" data-name="${esc(p.name)}"><span>${p.number}</span> ${esc(p.name)}</a></li>`)
    .join('\n            ');
  const ld = {
    '@context': 'https://schema.org',
    '@type': 'Person',
    name: 'Josean Araújo',
    description: t.meta.person,
    homeLocation: { '@type': 'Country', name: t.meta.country },
    knowsLanguage: ['pt', 'en', 'fr'],
    sameAs: [LINKEDIN],
  };

  const extra = `    <script type="application/ld+json">
      ${JSON.stringify(ld, null, 2).replace(/\n/g, "\n      ")}
    </script>
    <script>
      // Picks the hero mode before first paint, so the page height (and any #anchor) is right from the start.
      (function () {
        var d = document.documentElement;
        var reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
        var short = window.matchMedia('(max-height: 519px)').matches; // e.g. 200 % zoom on a laptop
        var wide = window.matchMedia('(min-width: 1024px) and (min-height: 600px)').matches;
        d.classList.remove('no-js');
        d.classList.add('js', reduced || short ? 'hero-static' : wide ? 'hero-scroll' : 'hero-compact');
        if (!reduced) d.classList.add('motion-ok');
      })();
    </script>
    <link rel="preload" as="image" href="/src/assets/img/hero-desktop-1672.webp" media="(min-width: 768px)" fetchpriority="high" />
    <script type="module" src="/src/main.js"></script>
`;

  return `<!doctype html>
<!-- Generated by scripts/build-pages.mjs from scripts/pages/home.mjs and src/i18n/${loc.code}.js: edit those, then run npm run pages. -->
<html lang="${loc.html}" class="no-js">
  ${head({
    loc,
    t,
    title: t.meta.title,
    description: t.meta.description,
    ogType: 'website',
    ogTitle: 'Josean Araújo · Inside the Creative Mind',
    ogDescription: t.meta.ogDescription,
    alternates,
    guess: loc.code === 'pt',
    extra,
  })}
  <body>
    <a class="skip-link" href="#conteudo">${esc(t.skip)}</a>

    <svg class="icon-sprite" aria-hidden="true" focusable="false">
      <symbol id="i-arrow-right" viewBox="0 0 24 24"><path d="M4 12h15m-6-6 6 6-6 6" /></symbol>
      <symbol id="i-arrow-down" viewBox="0 0 24 24"><path d="M12 4v15m-6-6 6 6 6-6" /></symbol>
      <symbol id="i-external" viewBox="0 0 24 24"><path d="M7 17 17 7M8 7h9v9" /></symbol>
      <symbol id="i-linkedin" viewBox="0 0 24 24"><path d="M4.5 9.5h3v10h-3zM6 4.6a1.7 1.7 0 1 1 0 3.4 1.7 1.7 0 0 1 0-3.4ZM10.5 9.5h2.9v1.4c.5-.9 1.7-1.7 3.4-1.7 3.2 0 3.7 2 3.7 4.7v5.6h-3v-5c0-1.2 0-2.7-1.7-2.7s-2 1.3-2 2.6v5.1h-3.3z" /></symbol>
      <symbol id="i-listen" viewBox="0 0 24 24"><circle cx="12" cy="12" r="8.5" /><path d="M12 8v4.5l3 1.8" /></symbol>
      <symbol id="i-shape" viewBox="0 0 24 24"><path d="M4 20 12 4l8 16H4Z" /><path d="M8.3 12h7.4" /></symbol>
      <symbol id="i-build" viewBox="0 0 24 24"><path d="M8 7 3 12l5 5M16 7l5 5-5 5M14 4l-4 16" /></symbol>
      ${GLOBE}
    </svg>

    ${header({ loc, t, alternates })}

    <!-- 01 / Hero, "Inside the Creative Mind". Scroll mode: the stage stays pinned while the portrait
         opens into planes, six project windows emerge, Automotives STA takes the portal and the
         camera goes through it. The name, the text and the links are live HTML. -->
    <div class="hero-track" id="inicio" data-hero-track>
      <section class="hero" aria-labelledby="hero-title">
        <div class="hero-stage" data-stage>
          <div class="scene" aria-hidden="true">
            <img class="h-bg" alt="" decoding="async" data-bg />
            <picture class="h-art" data-art>
              <source media="(max-width: 767px)" srcset="/src/assets/img/hero-mobile-640.webp 640w, /src/assets/img/hero-mobile-941.webp 941w" sizes="100vw" />
              <img
                src="/src/assets/img/hero-desktop-1672.webp"
                srcset="/src/assets/img/hero-desktop-800.webp 800w, /src/assets/img/hero-desktop-1200.webp 1200w, /src/assets/img/hero-desktop-1672.webp 1672w"
                sizes="100vw"
                width="1672"
                height="941"
                alt=""
                fetchpriority="high"
                data-art-img
              />
            </picture>
            <div class="h-planes" data-planes></div>
            <img class="h-layer h-portrait" alt="" decoding="async" data-layer="portrait" />
            <img class="h-layer h-rim" alt="" decoding="async" data-rim />
            <div class="h-windows" data-windows></div>
            <img class="h-layer h-josean" alt="" decoding="async" data-layer="josean" />
            <img class="h-portal" alt="" decoding="async" data-portal />
            <span class="h-tint" data-tint></span>
            <span class="h-sweep" data-sweep></span>
            <div class="h-full" data-full><img alt="" decoding="async" /></div>
            <svg class="h-light" data-light><path data-light-path /></svg>
          </div>

          <div class="wrap hero-copy" data-hero-copy>
            <div class="hero-head">
              <p class="eyebrow hero-eyebrow">${esc(t.hero.eyebrow)}</p>
              <h1 class="hero-title" id="hero-title">
                <span>Josean</span>
                <span>Araújo</span>
              </h1>
              <p class="hero-tagline">${esc(t.hero.tagline)}</p>
            </div>
            <div class="hero-foot">
              <p class="hero-intro">${esc(t.hero.intro)}</p>
              <div class="actions">
                <a class="btn btn--primary" href="#projetos">
                  <span>${esc(t.hero.explore)}</span>
                  ${ARROW('i-arrow-down')}
                </a>
                <a class="btn btn--quiet" href="#estudos">${esc(t.hero.all)}</a>
              </div>
            </div>
          </div>

          <!-- scene captions: they narrate the scene, so screen readers get them as plain text in order -->
          <div class="wrap hero-caption hero-caption--reveal" data-caption="reveal">
            <p class="eyebrow">${esc(t.hero.revealEyebrow)}</p>
            <p class="caption-title">${esc(t.hero.revealTitle)}</p>
            <ol class="caption-index">
              ${index}
            </ol>
          </div>
          <div class="wrap hero-caption hero-caption--select" data-caption="select">
            <p class="eyebrow"><span>01 / 0${projects.length}</span> ${esc(t.work.kicker)}</p>
            <p class="caption-title">${esc(by.sta.name)}</p>
            <p class="caption-sub">${esc(S.sta.tagline)}</p>
            <a class="btn btn--line" href="${studyUrl(loc, 'sta')}">
              <span>${esc(t.work.explore)}</span>
              ${ARROW('i-arrow-right')}
            </a>
          </div>

          <div class="hero-progress" aria-hidden="true"><span data-progress></span></div>
          <p class="scroll-cue" aria-hidden="true" data-cue>${esc(t.hero.cue)}</p>
        </div>
      </section>
    </div>

    <main id="conteudo" class="content" tabindex="-1" data-content>
      <!-- 02–03 / Projects. The hero lands in the first study: same image, same frame. -->
      <section class="projects" id="projetos" aria-labelledby="projetos-title">
        <h2 class="sr-only" id="projetos-title">${esc(t.work.title)}</h2>

        <nav class="rail" aria-label="${esc(t.work.rail)}" data-rail>
          <ol>
            ${rail}
          </ol>
        </nav>

        <!-- 01 · Automotives STA: car -> scan -> engine (crossfade, short scale, vertical mask) -->
        <article class="chapter chapter--sta" id="sta" aria-labelledby="sta-title" data-chapter="sta">
          <div class="sta-track" data-sta-track>
            <div class="sta-stage" data-sta-stage>
              <div class="sta-scene" aria-hidden="true">
                <img class="sta-car" src="/src/assets/img/sta-scan-1672.webp" srcset="/src/assets/img/sta-scan-1000.webp 1000w, /src/assets/img/sta-scan-1672.webp 1672w" sizes="100vw" width="1672" height="941" alt="" loading="lazy" decoding="async" />
                <img class="sta-car sta-car--lit" src="/src/assets/img/sta-scan-1672.webp" srcset="/src/assets/img/sta-scan-1000.webp 1000w, /src/assets/img/sta-scan-1672.webp 1672w" sizes="100vw" width="1672" height="941" alt="" loading="lazy" decoding="async" />
                <span class="sta-beam"></span>
                <div class="sta-engine">
                  <img src="/src/assets/img/sta-engine-1102.webp" srcset="/src/assets/img/sta-engine-661.webp 661w, /src/assets/img/sta-engine-1102.webp 1102w" sizes="(min-width: 1024px) 46vw, 90vw" width="1102" height="973" alt="" loading="lazy" decoding="async" />
                </div>
                <span class="sta-shade"></span>
              </div>
              <div class="wrap sta-copy">
                ${c('sta', 'btn--primary')}
              </div>
              <ol class="states" aria-label="${esc(t.work.states)}">
                ${S.sta.motion.map((m, i) => `<li data-state="${i}">${esc(m)}</li>`).join('\n                ')}
              </ol>
            </div>
          </div>
        </article>

        <!-- 02 · Isola: a round reflection becomes an orbit -->
        <article class="chapter chapter--light chapter--isola" id="isola" aria-labelledby="isola-title" data-chapter="isola" data-scene>
          <div class="wrap chapter-grid">
            ${c('isola', 'btn--dark')}
            <div class="isola-visual" aria-hidden="true">
              <span class="orbit-wrap orbit-wrap--back"><span class="orbit"></span><i></i><i></i><i></i><i></i><i></i><i></i><i></i></span>
              <img class="isola-scoop" src="/src/assets/img/isola-scoop-998.webp" srcset="/src/assets/img/isola-scoop-599.webp 599w, /src/assets/img/isola-scoop-998.webp 998w" sizes="(min-width: 1024px) 34vw, 70vw" width="998" height="992" alt="" loading="lazy" decoding="async" />
              <span class="orbit-wrap orbit-wrap--front"><span class="orbit"></span><i></i><i></i><i></i><i></i><i></i><i></i><i></i></span>
              <figure class="shot shot--isola">
                <img src="/src/assets/img/window-isola-640.webp" srcset="/src/assets/img/window-isola-640.webp 640w, /src/assets/img/window-isola-1024.webp 1024w" sizes="(min-width: 1024px) 22vw, 60vw" width="640" height="400" alt="" loading="lazy" decoding="async" />
              </figure>
            </div>
          </div>
        </article>

        <!-- 03 · Legend Nails: the orbit stretches into an editorial stroke -->
        <article class="chapter chapter--light chapter--legend" id="legend" aria-labelledby="legend-title" data-chapter="legend" data-scene>
          <div class="wrap chapter-grid chapter-grid--flip">
            <div class="legend-visual" aria-hidden="true">
              <figure class="shot shot--tall">
                <img src="/src/assets/img/concept-legend-720.webp" srcset="/src/assets/img/concept-legend-720.webp 720w, /src/assets/img/concept-legend-1024.webp 1024w" sizes="(min-width: 1024px) 30vw, 80vw" width="720" height="1080" alt="" loading="lazy" decoding="async" />
              </figure>
              <svg class="stroke" viewBox="0 0 600 260"><path pathLength="1" d="M8 196C96 70 214 40 300 118s170 104 284-60" /></svg>
            </div>
            ${c('legend', 'btn--dark')}
          </div>
        </article>

        <!-- 04–05 · the two barbershops, side by side: two identities for the same craft -->
        <div class="duo" data-scene>
          <header class="wrap duo-head" data-reveal>
            <p class="eyebrow">04 — 05</p>
            <p class="duo-title">${esc(t.work.duo)}</p>
          </header>
          <div class="wrap duo-grid">
            <article class="chapter chapter--orhan" id="orhan" aria-labelledby="orhan-title" data-chapter="orhan">
              <div class="duo-visual orhan-visual" aria-hidden="true">
                <img class="orhan-razor" src="/src/assets/img/orhan-razor-857.webp" srcset="/src/assets/img/orhan-razor-857.webp 857w, /src/assets/img/orhan-razor-1428.webp 1428w" sizes="(min-width: 1024px) 40vw, 90vw" width="857" height="564" alt="" loading="lazy" decoding="async" />
                <span class="orhan-edge"></span>
              </div>
              ${c('orhan', 'btn--primary')}
            </article>
            <article class="chapter chapter--bayro" id="bayro" aria-labelledby="bayro-title" data-chapter="bayro">
              <div class="duo-visual bayro-visual" aria-hidden="true">
                <img src="/src/assets/img/window-bayro-640.webp" srcset="/src/assets/img/window-bayro-640.webp 640w, /src/assets/img/window-bayro-1024.webp 1024w" sizes="(min-width: 1024px) 40vw, 90vw" width="640" height="400" alt="" loading="lazy" decoding="async" />
                <span class="bayro-cut"></span>
              </div>
              ${c('bayro', 'btn--primary')}
            </article>
          </div>
        </div>

        <!-- 06 · M&M Cleaning: the planes recompose as architecture -->
        <article class="chapter chapter--light chapter--mm" id="mm" aria-labelledby="mm-title" data-chapter="mm" data-scene>
          <div class="wrap chapter-grid">
            ${c('mm', 'btn--dark')}
            <div class="mm-visual" aria-hidden="true">
              <img class="mm-layer mm-layer--top" src="/src/assets/img/mm-room-861.webp" srcset="/src/assets/img/mm-room-517.webp 517w, /src/assets/img/mm-room-861.webp 861w" sizes="(min-width: 1024px) 36vw, 80vw" width="861" height="1000" alt="" loading="lazy" decoding="async" />
              <img class="mm-layer mm-layer--mid" src="/src/assets/img/mm-room-861.webp" srcset="/src/assets/img/mm-room-517.webp 517w, /src/assets/img/mm-room-861.webp 861w" sizes="(min-width: 1024px) 36vw, 80vw" width="861" height="1000" alt="" loading="lazy" decoding="async" />
              <img class="mm-layer mm-layer--base" src="/src/assets/img/mm-room-861.webp" srcset="/src/assets/img/mm-room-517.webp 517w, /src/assets/img/mm-room-861.webp 861w" sizes="(min-width: 1024px) 36vw, 80vw" width="861" height="1000" alt="" loading="lazy" decoding="async" />
            </div>
          </div>
        </article>
      </section>

      <!-- all six, as a plain list: the way in without the animation -->
      <section class="studies" id="estudos" aria-labelledby="estudos-title">
        <div class="wrap">
          <header class="section-head" data-reveal>
            <p class="eyebrow">01 — 0${projects.length}</p>
            <h2 class="section-title" id="estudos-title">${esc(t.list.title)}</h2>
            <p class="section-lead">${esc(t.list.lead)}</p>
          </header>
          <ol class="study-grid">
${projects.map((p) => card({ p, s: S[p.slug], t, loc })).join('\n')}
          </ol>
        </div>
      </section>

      <!-- 05 / About: a quieter pause, silver. The two roles come from Josean's CV (13/07/2026). -->
      <section class="about" id="sobre" aria-labelledby="sobre-title" data-scene>
        <div class="about-media" aria-hidden="true">
          <img src="/src/assets/img/about-1672.webp" srcset="/src/assets/img/about-1000.webp 1000w, /src/assets/img/about-1672.webp 1672w" sizes="(min-width: 1024px) 50vw, 100vw" width="1672" height="941" alt="" loading="lazy" decoding="async" data-parallax />
        </div>
        <div class="about-copy">
          <div class="about-inner" data-reveal>
            <p class="eyebrow">${esc(t.about.eyebrow)}</p>
            <h2 class="section-title" id="sobre-title">${esc(t.about.title)}</h2>
            ${t.about.paragraphs.map((x) => `<p>${esc(x)}</p>`).join('\n            ')}
            <section class="career" aria-labelledby="career-title">
              <h3 class="career-title" id="career-title">${esc(t.about.career)}</h3>
              <ol class="roles">
                ${t.about.roles.map(role).join('\n                ')}
              </ol>
            </section>
            <dl class="facts">
              ${t.about.facts.map(([k, v]) => `<div>\n                <dt>${esc(k)}</dt>\n                <dd>${esc(v)}</dd>\n              </div>`).join('\n              ')}
            </dl>
            <a class="link-arrow" href="${LINKEDIN}" target="_blank" rel="noopener">
              <span>${esc(t.about.linkedin)}</span>
              ${ARROW('i-external')}
              <span class="sr-only">${esc(t.newTab)}</span>
            </a>
          </div>
        </div>
      </section>

      <!-- 06 / Process -->
      <section class="process" id="processo" aria-labelledby="processo-title" data-scene>
        <div class="wrap">
          <header class="section-head" data-reveal>
            <p class="eyebrow">${esc(t.process.eyebrow)}</p>
            <h2 class="section-title" id="processo-title">${esc(t.process.title)}</h2>
          </header>
          <div class="steps-wrap">
          <span class="steps-line" aria-hidden="true"></span>
          <ol class="steps">
            ${t.process.steps
              .map(
                ([h, x], i) => `<li class="step" data-reveal>
              ${`<svg class="icon step-icon" aria-hidden="true"><use href="#${['i-listen', 'i-shape', 'i-build'][i]}" /></svg>`}
              <p class="step-num">0${i + 1}</p>
              <h3>${esc(h)}</h3>
              <p>${esc(x)}</p>
            </li>`,
              )
              .join('\n            ')}
          </ol>
          </div>
        </div>
      </section>

      <!-- 07 / Contact: the closing portal, one path -->
      <!-- TODO(portfolio): add email, GitHub or WhatsApp here only once the real addresses are confirmed (roteiro §07) -->
      <section class="contact" id="contato" aria-labelledby="contato-title">
        <div class="contact-media" aria-hidden="true">
          <img src="/src/assets/img/closing-1672.webp" srcset="/src/assets/img/closing-1000.webp 1000w, /src/assets/img/closing-1672.webp 1672w" sizes="100vw" width="1672" height="941" alt="" loading="lazy" decoding="async" />
        </div>
        <div class="wrap contact-inner">
          <div class="contact-copy" data-reveal>
            <p class="eyebrow">${esc(t.contact.eyebrow)}</p>
            <h2 class="contact-title" id="contato-title">
              <span>${esc(t.contact.title[0])}</span>
              <span>${esc(t.contact.title[1])}</span>
            </h2>
            <p class="section-lead">${esc(t.contact.lead)}</p>
            <a class="btn btn--primary btn--lg" href="${LINKEDIN}" target="_blank" rel="noopener">
              ${ARROW('i-linkedin')}
              <span>${esc(t.contact.cta)}</span>
              <span class="sr-only">${esc(t.newTab)}</span>
            </a>
          </div>
        </div>
      </section>
    </main>

    ${footer({ loc, t, note: t.footer.note })}
  </body>
</html>
`;
}
