// A study page (roteiro-secoes.md §04): name, sector and "concept study"; the opportunity; the
// direction; the interface (the concept mockup, which opens at full size); the movement (up to
// three states and a short script); Josean's role; next study and the way back.
import { projects } from '../../src/data/projects.js';
import { esc, img, head, header, footer, homeUrl, studyUrl, LOCALES, GLOBE } from './shared.mjs';

export function study(loc, t, i) {
  const p = projects[i];
  const s = t.studies[p.slug];
  const next = projects[(i + 1) % projects.length];
  const n = projects.length;
  const L = t.study;
  const alternates = Object.fromEntries(LOCALES.map((l) => [l.code, studyUrl(l, p.slug)]));
  const interfaceBlock = p.concept
    ? `<figure class="concept" data-reveal>
            <a class="concept-link" href="/studies/${p.slug}.webp" target="_blank" rel="noopener">
              <img src="${img(`concept-${p.slug}-1024`)}" srcset="${img(`concept-${p.slug}-720`)} 720w, ${img(`concept-${p.slug}-1024`)} 1024w" sizes="(min-width: 1024px) 46vw, 92vw" width="${p.concept.width}" height="${p.concept.height}" alt="${esc(L.conceptAlt(p.name))}" loading="lazy" decoding="async" />
              <span class="concept-zoom"><svg class="icon" aria-hidden="true"><use href="#i-expand" /></svg> ${esc(L.zoom)}<span class="sr-only">${esc(L.zoomSr)}</span></span>
            </a>
            <figcaption>${esc(L.conceptCaption)}</figcaption>
          </figure>`
    : `<p class="study-text concept-missing" data-reveal>${esc(L.conceptMissing)}</p>`;
  const prototype = p.prototype
    ? `<a class="btn btn--quiet" href="${p.prototype}" target="_blank" rel="noopener">
                <span>${esc(L.prototype)}</span>
                <svg class="icon" aria-hidden="true"><use href="#i-external" /></svg>
                <span class="sr-only">${esc(t.newTab)}</span>
              </a>`
    : '';
  const extra = `    <script>
      document.documentElement.classList.remove('no-js');
      document.documentElement.classList.add('js');
      if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches) document.documentElement.classList.add('motion-ok');
    </script>
    <script type="module" src="/src/study.js"></script>
`;

  return `<!doctype html>
<!-- Generated by scripts/build-pages.mjs from scripts/pages/study.mjs and src/i18n/${loc.code}.js: edit those, then run npm run pages. -->
<html lang="${loc.html}" class="no-js">
  ${head({
    loc,
    t,
    title: `${p.name} · ${L.kicker} · Josean Araújo`,
    description: L.description(p.name, s.proposal, s.role.replace(/\.$/, '').toLowerCase()),
    ogType: 'article',
    ogTitle: `${p.name} · ${L.kicker}`,
    ogDescription: s.proposal,
    alternates,
    extra,
  })}
  <body class="study-page" style="--accent: ${p.accent}">
    <a class="skip-link" href="#conteudo">${esc(t.skip)}</a>

    <svg class="icon-sprite" aria-hidden="true" focusable="false">
      <symbol id="i-arrow-right" viewBox="0 0 24 24"><path d="M4 12h15m-6-6 6 6-6 6" /></symbol>
      <symbol id="i-arrow-left" viewBox="0 0 24 24"><path d="M20 12H5m6-6-6 6 6 6" /></symbol>
      <symbol id="i-external" viewBox="0 0 24 24"><path d="M7 17 17 7M8 7h9v9" /></symbol>
      <symbol id="i-expand" viewBox="0 0 24 24"><path d="M14 4h6v6M10 20H4v-6M20 4l-7 7M4 20l7-7" /></symbol>
      ${GLOBE}
    </svg>

    ${header({ loc, t, alternates, study: true })}

    <main id="conteudo" class="study" tabindex="-1">
      <!-- 1 · name, sector, label -->
      <section class="study-hero" aria-labelledby="study-title">
        <div class="wrap study-hero-grid">
          <div class="study-intro" data-reveal>
            <a class="back" href="${homeUrl(loc)}#${p.slug}">
              <svg class="icon" aria-hidden="true"><use href="#i-arrow-left" /></svg>
              <span>${esc(L.back)}</span>
            </a>
            <p class="eyebrow"><span>${p.number} / 0${n}</span> ${esc(L.kicker)}</p>
            <h1 class="study-title" id="study-title">${esc(p.name)}</h1>
            <p class="case-sector">${esc(s.sector)}</p>
            <p class="study-lead">${esc(s.proposal)}</p>
          </div>
          <figure class="study-window" data-reveal>
            <img src="${img(`window-${p.slug}-1024`)}" srcset="${img(`window-${p.slug}-640`)} 640w, ${img(`window-${p.slug}-1024`)} 1024w" sizes="(min-width: 1024px) 50vw, 92vw" width="1024" height="640" alt="" fetchpriority="high" decoding="async" />
          </figure>
        </div>
      </section>

      <div class="wrap study-body">
        <!-- 2 · the opportunity -->
        <section class="study-block" aria-labelledby="oportunidade" data-reveal>
          <h2 class="study-h2" id="oportunidade"><span>02</span> ${esc(L.opportunity)}</h2>
          <p class="study-text">${esc(s.opportunity)}</p>
        </section>

        <!-- 3 · the direction -->
        <section class="study-block" aria-labelledby="direcao" data-reveal>
          <h2 class="study-h2" id="direcao"><span>03</span> ${esc(L.direction)}</h2>
          <dl class="direction">
${Object.entries(L.directionLabels)
  .map(([k, label]) => `            <div>\n              <dt>${esc(label)}</dt>\n              <dd>${esc(s.direction[k])}</dd>\n            </div>`)
  .join('\n')}
          </dl>
        </section>

        <!-- 4 · the interface -->
        <section class="study-block study-block--wide" aria-labelledby="interface">
          <h2 class="study-h2" id="interface" data-reveal><span>04</span> ${esc(L.interface)}</h2>
          <div class="interface-grid">
          ${interfaceBlock}
            <div class="interface-note" data-reveal>
              <p class="study-text">${esc(L.interfaceNote)}</p>
              <div class="actions">
              ${prototype}
              </div>
            </div>
          </div>
        </section>

        <!-- 5 · the movement -->
        <section class="study-block" aria-labelledby="movimento" data-reveal>
          <h2 class="study-h2" id="movimento"><span>05</span> ${esc(L.movement)}</h2>
          <ol class="motion-states">
${s.motion.map((m, j) => `            <li><span>${String(j + 1).padStart(2, '0')}</span> ${esc(m)}</li>`).join('\n')}
          </ol>
          <p class="study-text">${esc(s.script)}</p>
        </section>

        <!-- 6 · Josean's role -->
        <section class="study-block" aria-labelledby="papel" data-reveal>
          <h2 class="study-h2" id="papel"><span>06</span> ${esc(L.role)}</h2>
          <p class="study-text">${esc(s.role)}</p>
        </section>
      </div>

      <!-- 7 · next study and the way back -->
      <nav class="study-next" aria-label="${esc(L.nav)}">
        <div class="wrap study-next-inner">
          <a class="next-link" href="${studyUrl(loc, next.slug)}">
            <span class="eyebrow">${esc(L.next)}</span>
            <span class="next-name">${esc(next.name)}</span>
            <span class="next-line">${esc(t.studies[next.slug].tagline)}</span>
            <svg class="icon" aria-hidden="true"><use href="#i-arrow-right" /></svg>
          </a>
          <a class="back" href="${homeUrl(loc)}#estudos">
            <svg class="icon" aria-hidden="true"><use href="#i-arrow-left" /></svg>
            <span>${esc(L.all)}</span>
          </a>
        </div>
      </nav>
    </main>

    ${footer({ loc, t, note: t.footer.studyNote(p.name), study: true })}
  </body>
</html>
`;
}
